In [1]:
import pandas as pd
import seaborn as sb
import numpy as np
!pip install xlrd

Requirement already satisfied: xlrd in c:\users\ade\appdata\local\programs\python\python37\lib\site-packages (2.0.1)

[notice] A new release of pip is available: 23.0 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
ruta_archivo = r"\Users\Ade\src\data\2020datospanelconsumoalimentario.xlsx"
panel20_1 = pd.read_excel(ruta_archivo)
panel20_1

,CONSUMO EN HOGAR (Miles Euros),T.ESPAÑA,CATALUÑA,ARAGÓN,ILLES BALEARS,COMUNITAT VALENCIANA,REGIÓN DE MURCIA,ANDALUCÍA,COMUNIDAD DE MADRID,CASTILLA - LA MANCHA,EXTREMADURA,CASTILLA Y LEÓN,GALICIA,PRINCIPADO DE ASTURIAS,CANTABRIA,PAIS VASCO,LA RIOJA,C. FORAL DE NAVARRA,CANARIAS
0,.TOTAL ALIMENTACION,7.934825e+07,1.419434e+07,2.343943e+06,2.079831e+06,8.072972e+06,2.277991e+06,1.309760e+07,1.098971e+07,3.189511e+06,1.592526e+06,4.192015e+06,4.890844e+06,2.006396e+06,937286.912449,4.257823e+06,521999.271877,1.147528e+06,3.555941e+06
1,T.HUEVOS KGS,1.056606e+06,1.781836e+05,3.317559e+04,2.586739e+04,1.056056e+05,2.871375e+04,1.805147e+05,1.391675e+05,3.667164e+04,2.008388e+04,5.305614e+04,7.939235e+04,2.723924e+04,13833.245968,6.043571e+04,7427.220554,1.582405e+04,5.141411e+04
2,T.HUEVOS UNDS.,1.056606e+06,1.781836e+05,3.317559e+04,2.586739e+04,1.056056e+05,2.871375e+04,1.805147e+05,1.391675e+05,3.667164e+04,2.008388e+04,5.305614e+04,7.939235e+04,2.723924e+04,13833.245968,6.043571e+04,7427.220554,1.582405e+04,5.141411e+04
3,TOTAL HUEVOS GALLINA,1.044105e+06,1.759258e+05,3.247981e+04,2.547132e+04,1.044668e+05,2.836468e+04,1.778342e+05,1.375031e+05,3.625277e+04,1.986357e+04,5.252134e+04,7.895916e+04,2.714742e+04,13789.108400,5.937419e+04,7352.231000,1.573752e+04,5.106164e+04
4,OTRAS AVES,1.250112e+04,2.257783e+03,6.957772e+02,3.960751e+02,1.138820e+03,3.490707e+02,2.680533e+03,1.664436e+03,4.188646e+02,2.203062e+02,5.348003e+02,4.331870e+02,9.182728e+01,44.137568,1.061513e+03,74.989554,8.652619e+01,3.524696e+02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
676,BEBIDAS REFRESCAN.SG,8.274808e+04,8.553124e+03,1.052111e+03,1.937064e+03,7.952881e+03,2.441314e+03,2.628842e+04,1.007495e+04,4.958796e+03,2.600717e+03,3.179773e+03,3.567602e+03,9.124949e+02,962.152450,1.844202e+03,235.212677,3.755393e+02,5.811728e+03
677,HARINAS Y SEMOLAS SG,3.331599e+04,5.706617e+03,8.718194e+02,1.671611e+03,3.249763e+03,8.066712e+02,5.406322e+03,4.365735e+03,1.209193e+03,7.135652e+02,1.448107e+03,1.874993e+03,9.197054e+02,382.290738,1.123365e+03,180.928506,5.086107e+02,2.876692e+03
678,RESTO PRODUCTOS SG,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00
679,ALIMENTACION FRESCA,3.436848e+07,6.094847e+06,1.084729e+06,8.461241e+05,3.449841e+06,9.588209e+05,5.409473e+06,4.749991e+06,1.393183e+06,6.574645e+05,2.015064e+06,2.307092e+06,8.926138e+05,386480.980467,2.020339e+06,248597.088958,5.576151e+05,1.296202e+06
680,RESTO ALIMENTACION,4.497978e+07,8.099490e+06,1.259214e+06,1.233707e+06,4.623131e+06,1.319170e+06,7.688128e+06,6.239719e+06,1.796328e+06,9.350617e+05,2.176951e+06,2.583752e+06,1.113783e+06,550805.931982,2.237484e+06,273402.182919,5.899125e+05,2.259739e+06

In [3]:
panel20_1.columns

Index(['CONSUMO EN HOGAR (Miles Euros)', 'T.ESPAÑA', 'CATALUÑA', 'ARAGÓN',
       'ILLES BALEARS', 'COMUNITAT VALENCIANA', 'REGIÓN DE MURCIA',
       'ANDALUCÍA', 'COMUNIDAD DE MADRID', 'CASTILLA - LA MANCHA',
       'EXTREMADURA', 'CASTILLA Y LEÓN', 'GALICIA', 'PRINCIPADO DE ASTURIAS',
       'CANTABRIA', 'PAIS VASCO', 'LA RIOJA', 'C. FORAL DE NAVARRA',
       'CANARIAS'],
      dtype='object')

In [4]:
panel20_1.columns = ['ventas(miles €)', 'T.ESPAÑA', 'CATALUÑA', 'ARAGÓN',
       'ILLES BALEARS', 'COMUNITAT VALENCIANA', 'REGIÓN DE MURCIA',
       'ANDALUCÍA', 'COMUNIDAD DE MADRID', 'CASTILLA - LA MANCHA',
       'EXTREMADURA', 'CASTILLA Y LEÓN', 'GALICIA', 'PRINCIPADO DE ASTURIAS',
       'CANTABRIA', 'PAIS VASCO', 'LA RIOJA', 'C. FORAL DE NAVARRA',
       'CANARIAS']

In [5]:
panel20_1

,ventas(miles €),T.ESPAÑA,CATALUÑA,ARAGÓN,ILLES BALEARS,COMUNITAT VALENCIANA,REGIÓN DE MURCIA,ANDALUCÍA,COMUNIDAD DE MADRID,CASTILLA - LA MANCHA,EXTREMADURA,CASTILLA Y LEÓN,GALICIA,PRINCIPADO DE ASTURIAS,CANTABRIA,PAIS VASCO,LA RIOJA,C. FORAL DE NAVARRA,CANARIAS
0,.TOTAL ALIMENTACION,7.934825e+07,1.419434e+07,2.343943e+06,2.079831e+06,8.072972e+06,2.277991e+06,1.309760e+07,1.098971e+07,3.189511e+06,1.592526e+06,4.192015e+06,4.890844e+06,2.006396e+06,937286.912449,4.257823e+06,521999.271877,1.147528e+06,3.555941e+06
1,T.HUEVOS KGS,1.056606e+06,1.781836e+05,3.317559e+04,2.586739e+04,1.056056e+05,2.871375e+04,1.805147e+05,1.391675e+05,3.667164e+04,2.008388e+04,5.305614e+04,7.939235e+04,2.723924e+04,13833.245968,6.043571e+04,7427.220554,1.582405e+04,5.141411e+04
2,T.HUEVOS UNDS.,1.056606e+06,1.781836e+05,3.317559e+04,2.586739e+04,1.056056e+05,2.871375e+04,1.805147e+05,1.391675e+05,3.667164e+04,2.008388e+04,5.305614e+04,7.939235e+04,2.723924e+04,13833.245968,6.043571e+04,7427.220554,1.582405e+04,5.141411e+04
3,TOTAL HUEVOS GALLINA,1.044105e+06,1.759258e+05,3.247981e+04,2.547132e+04,1.044668e+05,2.836468e+04,1.778342e+05,1.375031e+05,3.625277e+04,1.986357e+04,5.252134e+04,7.895916e+04,2.714742e+04,13789.108400,5.937419e+04,7352.231000,1.573752e+04,5.106164e+04
4,OTRAS AVES,1.250112e+04,2.257783e+03,6.957772e+02,3.960751e+02,1.138820e+03,3.490707e+02,2.680533e+03,1.664436e+03,4.188646e+02,2.203062e+02,5.348003e+02,4.331870e+02,9.182728e+01,44.137568,1.061513e+03,74.989554,8.652619e+01,3.524696e+02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
676,BEBIDAS REFRESCAN.SG,8.274808e+04,8.553124e+03,1.052111e+03,1.937064e+03,7.952881e+03,2.441314e+03,2.628842e+04,1.007495e+04,4.958796e+03,2.600717e+03,3.179773e+03,3.567602e+03,9.124949e+02,962.152450,1.844202e+03,235.212677,3.755393e+02,5.811728e+03
677,HARINAS Y SEMOLAS SG,3.331599e+04,5.706617e+03,8.718194e+02,1.671611e+03,3.249763e+03,8.066712e+02,5.406322e+03,4.365735e+03,1.209193e+03,7.135652e+02,1.448107e+03,1.874993e+03,9.197054e+02,382.290738,1.123365e+03,180.928506,5.086107e+02,2.876692e+03
678,RESTO PRODUCTOS SG,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00
679,ALIMENTACION FRESCA,3.436848e+07,6.094847e+06,1.084729e+06,8.461241e+05,3.449841e+06,9.588209e+05,5.409473e+06,4.749991e+06,1.393183e+06,6.574645e+05,2.015064e+06,2.307092e+06,8.926138e+05,386480.980467,2.020339e+06,248597.088958,5.576151e+05,1.296202e+06
680,RESTO ALIMENTACION,4.497978e+07,8.099490e+06,1.259214e+06,1.233707e+06,4.623131e+06,1.319170e+06,7.688128e+06,6.239719e+06,1.796328e+06,9.350617e+05,2.176951e+06,2.583752e+06,1.113783e+06,550805.931982,2.237484e+06,273402.182919,5.899125e+05,2.259739e+06

In [6]:
panel20_1_tortilla = panel20_1[panel20_1["ventas(miles €)"].str.contains("tortilla|.TOTAL ALIMENTACION", case=False)]
panel20_1_tortilla

,ventas(miles €),T.ESPAÑA,CATALUÑA,ARAGÓN,ILLES BALEARS,COMUNITAT VALENCIANA,REGIÓN DE MURCIA,ANDALUCÍA,COMUNIDAD DE MADRID,CASTILLA - LA MANCHA,EXTREMADURA,CASTILLA Y LEÓN,GALICIA,PRINCIPADO DE ASTURIAS,CANTABRIA,PAIS VASCO,LA RIOJA,C. FORAL DE NAVARRA,CANARIAS
0,.TOTAL ALIMENTACION,7.934825e+07,1.419434e+07,2.343943e+06,2.079831e+06,8.072972e+06,2.277991e+06,1.309760e+07,1.098971e+07,3.189511e+06,1.592526e+06,4.192015e+06,4.890844e+06,2.006396e+06,937286.912449,4.257823e+06,521999.271877,1.147528e+06,3.555941e+06
559,TORTILLAS REFRIGERAD,6.822830e+04,1.302519e+04,2.894986e+03,1.514970e+03,5.325551e+03,1.931639e+03,1.302383e+04,1.149187e+04,2.776329e+03,1.420579e+03,3.934569e+03,1.760323e+03,1.143839e+03,684.010550,2.929843e+03,507.094070,1.101661e+03,2.762009e+03
672,TORTILLAS REFRIGE.SG,4.786603e+04,7.592625e+03,1.901490e+03,1.184837e+03,3.956858e+03,1.592686e+03,9.613499e+03,8.344144e+03,2.180240e+03,8.918202e+02,3.014764e+03,1.295424e+03,8.078614e+02,493.182100,2.063551e+03,426.263515,7.445703e+02,1.762214e+03

In [7]:
totales_sum = panel20_1_tortilla.iloc[[1, 2]].sum()
#se añade el valor obtenido al df completo
panel20_kg_tortilla = panel20_1_tortilla.append(totales_sum, ignore_index=True)
panel20_kg = pd.DataFrame (panel20_kg_tortilla)
panel20_kg

,ventas(miles €),T.ESPAÑA,CATALUÑA,ARAGÓN,ILLES BALEARS,COMUNITAT VALENCIANA,REGIÓN DE MURCIA,ANDALUCÍA,COMUNIDAD DE MADRID,CASTILLA - LA MANCHA,EXTREMADURA,CASTILLA Y LEÓN,GALICIA,PRINCIPADO DE ASTURIAS,CANTABRIA,PAIS VASCO,LA RIOJA,C. FORAL DE NAVARRA,CANARIAS
0,.TOTAL ALIMENTACION,7.934825e+07,1.419434e+07,2.343943e+06,2.079831e+06,8.072972e+06,2.277991e+06,1.309760e+07,1.098971e+07,3.189511e+06,1.592526e+06,4.192015e+06,4.890844e+06,2.006396e+06,937286.912449,4.257823e+06,521999.271877,1.147528e+06,3.555941e+06
1,TORTILLAS REFRIGERAD,6.822830e+04,1.302519e+04,2.894986e+03,1.514970e+03,5.325551e+03,1.931639e+03,1.302383e+04,1.149187e+04,2.776329e+03,1.420579e+03,3.934569e+03,1.760323e+03,1.143839e+03,684.010550,2.929843e+03,507.094070,1.101661e+03,2.762009e+03
2,TORTILLAS REFRIGE.SG,4.786603e+04,7.592625e+03,1.901490e+03,1.184837e+03,3.956858e+03,1.592686e+03,9.613499e+03,8.344144e+03,2.180240e+03,8.918202e+02,3.014764e+03,1.295424e+03,8.078614e+02,493.182100,2.063551e+03,426.263515,7.445703e+02,1.762214e+03
3,TORTILLAS REFRIGERADTORTILLAS REFRIGE.SG,1.160943e+05,2.061782e+04,4.796476e+03,2.699807e+03,9.282409e+03,3.524325e+03,2.263733e+04,1.983602e+04,4.956569e+03,2.312399e+03,6.949332e+03,3.055748e+03,1.951700e+03,1177.192650,4.993394e+03,933.357585,1.846232e+03,4.524223e+03

In [8]:
#datos de españa total y tortillas
panel20_España = panel20_kg.iloc[[0,3], 0:2]
panel20_España

                            ventas(miles €)      T.ESPAÑA
0                       .TOTAL ALIMENTACION  7.934825e+07
3  TORTILLAS REFRIGERADTORTILLAS REFRIGE.SG  1.160943e+05

In [9]:
#datos de españa total y tortillas
panel20_CCAA = panel20_kg.drop(panel20_kg.columns[1], axis=1).iloc[[3], :]
panel20_CCAA

,ventas(miles €),CATALUÑA,ARAGÓN,ILLES BALEARS,COMUNITAT VALENCIANA,REGIÓN DE MURCIA,ANDALUCÍA,COMUNIDAD DE MADRID,CASTILLA - LA MANCHA,EXTREMADURA,CASTILLA Y LEÓN,GALICIA,PRINCIPADO DE ASTURIAS,CANTABRIA,PAIS VASCO,LA RIOJA,C. FORAL DE NAVARRA,CANARIAS
3,TORTILLAS REFRIGERADTORTILLAS REFRIGE.SG,20617.8176,4796.4761,2699.8065,9282.4089,3524.32453,22637.3333,19836.0152,4956.5692,2312.3992,6949.3323,3055.74758,1951.70045,1177.19265,4993.3937,933.357585,1846.2318,4524.22295

In [10]:
# exporta el DataFrame 
panel20_kg.to_csv('/Users/Ade/src/data/panel20_kg.csv', index=False)
panel20_España.to_csv('/Users/Ade/src/data/panel20_España.csv', index=False)
panel20_CCAA.to_csv('/Users/Ade/src/data/panel20_CCAA.csv', index=False)

si quiero importar todas las hojas 
panel20_resto = pd. concat (pd. read_excel ('2020datospanelconsumoalimentario.xlsx', sheet_name = None ), ignore_index = True )
panel20_resto