In [1]:
import pandas as pd
from functools import reduce
import matplotlib.pyplot as plt

In [2]:
ruta_archivo = r"\Users\Ade\src\data\2019datospanelconsumoalimentario.xlsx"
panel19_kg = pd.read_excel(ruta_archivo)
panel19_kg

,TAM VALOR (Miles Euros),T.ESPAÑA,CATALUÑA,ARAGÓN,ILLES BALEARS,COMUNITAT VALENCIANA,REGIÓN DE MURCIA,ANDALUCÍA,COMUNIDAD DE MADRID,CASTILLA - LA MANCHA,EXTREMADURA,CASTILLA Y LEÓN,GALICIA,PRINCIPADO DE ASTURIAS,CANTABRIA,PAIS VASCO,LA RIOJA,C. FORAL DE NAVARRA,CANARIAS
0,.TOTAL ALIMENTACION,6.950313e+07,1.254206e+07,2.011979e+06,1.801109e+06,7.162241e+06,1.971766e+06,1.143558e+07,9.458425e+06,2.802768e+06,1.456337e+06,3.772033e+06,4.435241e+06,1.705766e+06,864618.617511,3.650009e+06,448146.758456,960675.177360,3.024377e+06
1,T.HUEVOS KGS,8.994396e+05,1.493918e+05,2.648733e+04,2.048183e+04,9.431858e+04,2.501852e+04,1.551861e+05,1.144731e+05,3.118275e+04,1.917179e+04,4.866146e+04,6.832613e+04,2.141420e+04,12881.430078,5.135764e+04,6171.365230,11939.445884,4.297613e+04
2,T.HUEVOS UNDS.,8.994396e+05,1.493918e+05,2.648733e+04,2.048183e+04,9.431858e+04,2.501852e+04,1.551861e+05,1.144731e+05,3.118275e+04,1.917179e+04,4.866146e+04,6.832613e+04,2.141420e+04,12881.430078,5.135764e+04,6171.365230,11939.445884,4.297613e+04
3,TOTAL HUEVOS GALLINA,8.880578e+05,1.473333e+05,2.587336e+04,2.014030e+04,9.317479e+04,2.475345e+04,1.526895e+05,1.131072e+05,3.078367e+04,1.906070e+04,4.794075e+04,6.782019e+04,2.131553e+04,12837.881600,5.062759e+04,6046.148700,11841.481300,4.271198e+04
4,HUEVOS GALLINA,7.452910e+05,1.340594e+05,2.045845e+04,1.824485e+04,8.423448e+04,2.251168e+04,1.203130e+05,1.056445e+05,2.666793e+04,1.363350e+04,3.762021e+04,3.498489e+04,1.729346e+04,10269.493000,4.673431e+04,5439.181300,10589.925000,3.659179e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
681,GASEOSAS&BEBID.REF.SG,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00
682,BEBIDAS REFRESCAN.SG,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00
683,HARINAS Y SEMOLAS SG,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00
684,OTROS PROD.EN PESO SG,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00
685,OTROS PROD.EN VOL. SG,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00

In [3]:
panel19_kg.columns = ['ventas(miles €)', 'ESPAÑA', 'CATALUÑA', 'ARAGÓN', 'ILLES BALEARS',
       'COMUNITAT VALENCIANA', 'REGIÓN DE MURCIA', 'ANDALUCÍA',
       'COMUNIDAD DE MADRID', 'CASTILLA - LA MANCHA', 'EXTREMADURA',
       'CASTILLA Y LEÓN', 'GALICIA', 'PRINCIPADO DE ASTURIAS', 'CANTABRIA',
       'PAIS VASCO', 'LA RIOJA', 'C. FORAL DE NAVARRA', 'CANARIAS']

In [4]:
#aqui extractado kg vendidos por CCAA y por total alimentacion y especifico
panel19_kg_torti = panel19_kg[panel19_kg["ventas(miles €)"].str.contains("tortilla|.TOTAL ALIMENTACION", case=False)]
panel19_kg_torti

,ventas(miles €),ESPAÑA,CATALUÑA,ARAGÓN,ILLES BALEARS,COMUNITAT VALENCIANA,REGIÓN DE MURCIA,ANDALUCÍA,COMUNIDAD DE MADRID,CASTILLA - LA MANCHA,EXTREMADURA,CASTILLA Y LEÓN,GALICIA,PRINCIPADO DE ASTURIAS,CANTABRIA,PAIS VASCO,LA RIOJA,C. FORAL DE NAVARRA,CANARIAS
0,.TOTAL ALIMENTACION,6.950313e+07,1.254206e+07,2.011979e+06,1.801109e+06,7.162241e+06,1.971766e+06,1.143558e+07,9.458425e+06,2.802768e+06,1.456337e+06,3.772033e+06,4.435241e+06,1.705766e+06,864618.617511,3.650009e+06,448146.758456,960675.17736,3.024377e+06
566,TORTILLAS REFRIGERAD,6.897601e+04,1.275482e+04,2.680066e+03,1.571362e+03,5.392339e+03,1.746361e+03,1.524034e+04,1.223913e+04,2.345623e+03,1.330493e+03,3.307726e+03,1.188747e+03,1.075814e+03,915.281420,2.259941e+03,430.485360,1294.34621,3.203143e+03
678,TORTILLAS REFRIGE.SG,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.00000,0.000000e+00

In [5]:
# suma los valores individuales de los datos de los tipos de tortilla
totales_sum = panel19_kg_torti.iloc[[1, 2]].sum()
#se añade el valor obtenido al df completo
panel19_kg_tortilla = panel19_kg_torti.append(totales_sum, ignore_index=True)
panel19_kg_tortilla = pd.DataFrame (panel19_kg_tortilla)
panel19_kg_tortilla

,ventas(miles €),ESPAÑA,CATALUÑA,ARAGÓN,ILLES BALEARS,COMUNITAT VALENCIANA,REGIÓN DE MURCIA,ANDALUCÍA,COMUNIDAD DE MADRID,CASTILLA - LA MANCHA,EXTREMADURA,CASTILLA Y LEÓN,GALICIA,PRINCIPADO DE ASTURIAS,CANTABRIA,PAIS VASCO,LA RIOJA,C. FORAL DE NAVARRA,CANARIAS
0,.TOTAL ALIMENTACION,6.950313e+07,1.254206e+07,2.011979e+06,1.801109e+06,7.162241e+06,1.971766e+06,1.143558e+07,9.458425e+06,2.802768e+06,1.456337e+06,3.772033e+06,4.435241e+06,1.705766e+06,864618.617511,3.650009e+06,448146.758456,960675.17736,3.024377e+06
1,TORTILLAS REFRIGERAD,6.897601e+04,1.275482e+04,2.680066e+03,1.571362e+03,5.392339e+03,1.746361e+03,1.524034e+04,1.223913e+04,2.345623e+03,1.330493e+03,3.307726e+03,1.188747e+03,1.075814e+03,915.281420,2.259941e+03,430.485360,1294.34621,3.203143e+03
2,TORTILLAS REFRIGE.SG,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.00000,0.000000e+00
3,TORTILLAS REFRIGERADTORTILLAS REFRIGE.SG,6.897601e+04,1.275482e+04,2.680066e+03,1.571362e+03,5.392339e+03,1.746361e+03,1.524034e+04,1.223913e+04,2.345623e+03,1.330493e+03,3.307726e+03,1.188747e+03,1.075814e+03,915.281420,2.259941e+03,430.485360,1294.34621,3.203143e+03

In [6]:
#datos de españa total y tortillas
panel19_España = panel19_kg_tortilla.iloc[[0,3], 0:2]
panel19_España

                            ventas(miles €)        ESPAÑA
0                       .TOTAL ALIMENTACION  6.950313e+07
3  TORTILLAS REFRIGERADTORTILLAS REFRIGE.SG  6.897601e+04

In [7]:
#datos de españa total y tortillas
panel19_CCAA = panel19_kg_tortilla.drop(panel19_kg_tortilla.columns[1], axis=1).iloc[[3], :]
panel19_CCAA

,ventas(miles €),CATALUÑA,ARAGÓN,ILLES BALEARS,COMUNITAT VALENCIANA,REGIÓN DE MURCIA,ANDALUCÍA,COMUNIDAD DE MADRID,CASTILLA - LA MANCHA,EXTREMADURA,CASTILLA Y LEÓN,GALICIA,PRINCIPADO DE ASTURIAS,CANTABRIA,PAIS VASCO,LA RIOJA,C. FORAL DE NAVARRA,CANARIAS
3,TORTILLAS REFRIGERADTORTILLAS REFRIGE.SG,12754.8249,2680.0658,1571.36175,5392.3392,1746.36114,15240.337,12239.1256,2345.6232,1330.49318,3307.7258,1188.74653,1075.81386,915.28142,2259.9413,430.48536,1294.34621,3203.1428

In [8]:
# exporta el DataFrame 
panel19_kg.to_csv('/Users/Ade/src/data/panel19_kg.csv', index=False)
panel19_España.to_csv('/Users/Ade/src/data/panel19_España.csv', index=False)
panel19_CCAA.to_csv('/Users/Ade/src/data/panel19_CCAA.csv', index=False)

si quiero importar todas las hojas 
panel20_resto = pd. concat (pd. read_excel ('2020datospanelconsumoalimentario.xlsx', sheet_name = None ), ignore_index = True )
panel20_resto